// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { Component, Input, TemplateRef } from '@angular/core';

@Component({
    selector: 'ks-grid',
    template: '',
})
export class KsGridComponent {
    @Input() public errorTemplate: TemplateRef<any>;
}
