// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { Deferred } from '@src/app/core/helpers/deferred';
import { EventEmitter } from '@angular/core';

export interface AsyncEvent {
    data: any;
    resolve: (handlerResult: Promise<any>) => void;
}

export function asyncEmit(emitter: EventEmitter<AsyncEvent>, eventData: any): Promise<any> {
    const deferred = new Deferred<any>();

    const event: AsyncEvent = {
        data: eventData,
        resolve: (handlerResult: Promise<any>) => {
            if (handlerResult instanceof Promise) {
                handlerResult.then((...args) => deferred.resolve(...args)).catch((err) => deferred.reject(err));
            } else {
                deferred.resolve();
            }
        }
    };

    emitter.emit(event);
    return deferred.promise;
}
