// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// You can write your custom code in the home.component.ts file instead.
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { AfterViewInit, Component, Injector } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { Observable, Subject } from 'rxjs';

import { InitDataServiceOptions, combineObservables, getDataObservable } from '@src/app/core/data/helpers/data-service-utils';
import { DataServiceConfig, DataServiceFactory } from '@src/app/core/data/helpers/data-service.factory';
import { EventsService } from '@src/app/core/services/events.service';
import { NavigationService } from '@src/app/core/services/navigation.service';
import { UtilsService } from '@src/app/core/services/utils.service';

@Component({
    templateUrl: './home.component.html',
    styleUrls: ['./home.component.css']
})
export class HomeViewBaseComponent implements AfterViewInit {
    public config = {
        label0: {
            forAttribute: '',
            textKey: 'modules.System.views.home.components.label0.text'
        },
        image0: {
            navigateUrl: '',
            alt: ''
        }
    };

    public data: Observable<any>;
    public loading: Observable<{ [key: string]: boolean }>;

    protected activatedRoute: ActivatedRoute;
    protected afterViewInit = new Subject<any>();
    protected eventsService: EventsService;
    protected navigationService: NavigationService;
    protected serviceFactory: DataServiceFactory;
    protected utilsService: UtilsService;

    constructor(public injector: Injector) {
        this.activatedRoute = injector.get(ActivatedRoute);
        this.eventsService = injector.get(EventsService);
        this.navigationService = injector.get(NavigationService);
        this.serviceFactory = injector.get(DataServiceFactory);
        this.utilsService = injector.get(UtilsService);

        const { dataServices, observables, loading } = this.initData(this.getDataConfig());

        this.data = getDataObservable({ dataServices, observables });
        this.loading = combineObservables(loading);
    }

    public ngAfterViewInit(): void {
        this.afterViewInit.next();
    }

    protected getDataConfig(): { [key: string]: DataServiceConfig } {
        return {};
    }

    protected initData(config: { [key: string]: DataServiceConfig }) {
        return {
            dataServices: {},
            observables: {},
            loading: {}
        };
    }
}
