// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { NO_ERRORS_SCHEMA, NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SharedModule } from '@src/app/shared/shared.module';
import { MainRoutingModule } from '@src/app/modules/main/main-routing.module';

import { CustomersViewBaseComponent } from '@src/app/modules/main/customers/customers.base.component';
import { CustomersViewComponent } from '@src/app/modules/main/customers/customers.component';

import { config, transformConfig } from '@src/app/modules/main/main.config';

const configMeta: NgModule = {
    providers: [...config.providers],
    declarations: [CustomersViewBaseComponent, CustomersViewComponent, ...config.declarations],
    imports: [CommonModule, SharedModule, MainRoutingModule, ...config.imports],
    exports: [...config.exports],
    entryComponents: [...config.entryComponents],
    bootstrap: [...config.bootstrap],
    schemas: [NO_ERRORS_SCHEMA, ...config.schemas],
    jit: config.jit
};

if (config.id) {
    configMeta.id = config.id;
}

transformConfig(configMeta);

@NgModule(configMeta)
export class MainModule {}
