// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { NgModule } from '@angular/core';
import { Routes } from '@angular/router';
import { NativeScriptRouterModule } from 'nativescript-angular/router';
import { CustomersViewComponent } from '@src/app/modules/main/customers/customers.component';
import { AuthenticationGuardService } from '@src/app/core/auth/authentication-guard.service';

import * as routeConfig from '@src/app/modules/main/main-routing.config';

const routes: Routes = [
    {
        path: 'customers',
        canActivate: [AuthenticationGuardService],
        runGuardsAndResolvers: 'always',
        component: CustomersViewComponent
    },
    ...routeConfig.config.routes
];

const routeConfigAsAny = routeConfig as any;
if (routeConfigAsAny.transformRoutes) {
    routeConfigAsAny.transformRoutes(routes);
}

@NgModule({
    imports: [NativeScriptRouterModule.forChild(routes)],
    exports: [NativeScriptRouterModule]
})
export class MainRoutingModule {}
