// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { Component, ElementRef, Input, OnInit } from '@angular/core';
import { isAndroid } from 'tns-core-modules/platform';
import { ActivatedRoute } from '@angular/router';
import { ExtendedNavigationExtras } from 'nativescript-angular/router/router-extensions';
import { EventData } from 'tns-core-modules/data/observable';
import { NavigationService } from '@src/app/core/services/navigation.service';
import { SideDrawerService } from '@src/app/core/services/side-drawer.service';

@Component({
    selector: 'ks-button',
    templateUrl: './button.component.html'
})
export class KSButtonComponent implements OnInit {
    constructor(
        private el: ElementRef,
        private sideDrawerService: SideDrawerService,
        protected navigationService: NavigationService,
        protected activatedRoute: ActivatedRoute) { }

    ngOnInit(): void {
        if (isAndroid) {
            const nativeElement = this.el.nativeElement;

            nativeElement.once('loaded', () => nativeElement.firstChild
              .nativeViewProtected.setMinWidth(nativeElement.firstChild.style.minWidth));
        }
    }

    public onSideDrawerOpen(args: EventData) {
        this.sideDrawerService.open();
    }

    public onGoBack(args: EventData) {
        if (this.canGoBack()) {
            this.goBack();
        }
    }

    private canGoBack(activatedRoute: ActivatedRoute = this.activatedRoute) {
        return this.navigationService.canGoBack(activatedRoute);
    }

    private goBack(activatedRoute: ActivatedRoute = this.activatedRoute) {
        return this.navigationService.goBack(activatedRoute);
    }
}
