// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { Component, ViewChild, EventEmitter, Input } from '@angular/core';

import { AutoCompleteComponent } from '@progress/kendo-angular-dropdowns';

import { KsDropDownBaseComponent } from '@src/app/shared/components/drop-down.base.component';

@Component({
    selector: 'ks-auto-complete',
    templateUrl: './auto-complete.component.html'
})
export class KsAutoCompleteComponent extends KsDropDownBaseComponent {
    @ViewChild('kendoComponent', { static: true }) public kendoComponent: AutoCompleteComponent;
    @Input() public style: any;

    protected getFilterFieldName(): string {
        return this.config.dataTextField;
    }

    protected getChildFilterChange(): EventEmitter<string> {
        return this.kendoComponent.filterChange;
    }

    protected openPopup(): void {
        this.kendoComponent.toggle(true);
    }
}
