// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { Component, OnInit, Input, forwardRef } from '@angular/core';
import { NG_VALUE_ACCESSOR } from '@angular/forms';
import { KsInputBaseComponent } from '@src/app/shared/components/input.base.component';

@Component({
    selector: 'ks-radio-button-list',
    templateUrl: './radio-button-list.component.html',
    styles: [
        `
        .ks-radio-button-list {
            min-height: 24px;
            overflow: auto;
            padding: 0;
            list-style: none;
        }

        .ks-radio-button-list li {
            padding: 2px;
        }

        .ks-radio-button-list.-horizontal {
            display: flex;
            align-items: center;
        }

        .ks-radio-button-list.-horizontal li {
            white-space: nowrap;
        }

        .ks-radio-button-list.-horizontal li + li {
            margin-left: 10px;
        }
        `
    ],
    providers: [
        {
            provide: NG_VALUE_ACCESSOR,
            useExisting: forwardRef(() => KsRadioButtonListComponent),
            multi: true
        }
    ]
})
export class KsRadioButtonListComponent extends KsInputBaseComponent implements OnInit {
    @Input() public name: string;
    @Input() public data: Array<any>;
    @Input() public style: any;

    public ngOnInit(): void {
        this.style = this.getStyle();
    }

    public changeHandler(event: any): void {
        const value = event && event.srcElement && event.srcElement.value;
        super.updateValue(this.config.valuePrimitive ? value[this.config.dataValueField] : value);
    }

    protected isChecked(item): boolean {
        if (!this.value) {
            return false;
        }

        const value = this.config.valuePrimitive ? this.value : this.value[this.config.dataValueField];
        return item[this.config.dataValueField] === value;
    }

    protected getInputId(index): string {
        return `${this.id}_${index}`;
    }

    protected getStyle() {
        const style = {};

        if (this.config.height) {
            style['height'] =  `${this.config.height}px`;
        }

        if (this.config.maxHeight) {
            style['max-height'] = `${this.config.maxHeight}px`;
        }

        return style;
    }
}
