// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { Injectable } from '@angular/core';
import { Observable, Subject } from 'rxjs';
import { filter } from 'rxjs/operators';

export interface Event {
    id: string;
    payload?: { [key: string]: any };
}

@Injectable()
export class EventsService {
    private eventsSource: Subject<any> = new Subject<any>();

    get events(): Observable<any> {
        return this.eventsSource.asObservable();
    }

    public next(event: Event): void {
        this.eventsSource.next(event);
    }

    public filter(eventName: string) {
        return this.events.pipe(filter(event => event.id === eventName));
    }
}
