// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { Injectable } from '@angular/core';
import { Location } from '@angular/common';
import { Router, ActivatedRoute } from '@angular/router';

@Injectable()
export class NavigationService {
    constructor(private router: Router, private location: Location) {}

    public navigate(command: any[], extras: any = {}) {
        extras.replaceUrl = extras.clearHistory;
        delete extras.clearHistory;
        this.router.navigate(command, extras);
    }

    public goBack(activatedRoute: ActivatedRoute) {
        return this.location.back();
    }
}
