// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { Injectable } from '@angular/core';
import { BehaviorSubject, Observable } from 'rxjs';
import * as Connectivity from 'tns-core-modules/connectivity';

@Injectable()
export class NetworkMonitoringService {
    public readonly connectionObservable: Observable<boolean>;
    public isOnline: boolean;

    private isOnlineSubject: BehaviorSubject<boolean>;

    constructor() {
        this.isOnline = this.getOnlineStatus(Connectivity.getConnectionType());
        this.isOnlineSubject = new BehaviorSubject(this.isOnline);
        this.connectionObservable = this.isOnlineSubject.asObservable();

        Connectivity.startMonitoring(connectionType => {
            this.isOnline = this.getOnlineStatus(connectionType);
            this.isOnlineSubject.next(this.isOnline);
        });
    }

    private getOnlineStatus(connectionType: number): boolean {
        return connectionType === Connectivity.connectionType.wifi
            || connectionType === Connectivity.connectionType.mobile;
    }
}
