// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { Injectable } from '@angular/core';
import { BehaviorSubject, Observable } from 'rxjs';

@Injectable()
export class NetworkMonitoringService {
    public readonly connectionObservable: Observable<boolean>;
    public isOnline: boolean;

    private isOnlineSubject: BehaviorSubject<boolean>;

    constructor() {
        this.isOnline = navigator.onLine;
        this.isOnlineSubject = new BehaviorSubject(this.isOnline);
        this.connectionObservable = this.isOnlineSubject.asObservable();

        window.addEventListener('offline', () => this.updateStatus({ isOnline: false }));
        window.addEventListener('online', () => this.updateStatus({ isOnline: true }));
    }

    private updateStatus({ isOnline }) {
        this.isOnline = isOnline;
        this.isOnlineSubject.next(this.isOnline);
    }
}
