// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { Component, Input } from '@angular/core';
import { Router } from '@angular/router';

import { AuthenticationService } from '@src/app/core/auth/authentication.service';

@Component({
    selector: 'ks-user-drop-down',
    templateUrl: './user-drop-down.component.html',
})
export class KsUserDropDownComponent {
    @Input() public style: any;
    public isMenuVisible = false;

    get isAuthenticated() {
        return this.authenticationService.isAuthenticated;
    }

    constructor(private router: Router, private authenticationService: AuthenticationService) {}

    public signIn() {
        this.authenticationService.authenticate();
    }

    public signOut() {
        this.authenticationService.signOut()
            .toPromise()
            .then(() => {
                this.router.navigate([this.router.routerState.snapshot.url]);
            });
    }
}
