// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { Component, Input, Injector } from '@angular/core';

@Component({
    selector: 'ks-hamburger-button',
    templateUrl: './hamburger-button.component.html',
})
export class KsHamburgerButtonComponent {
    @Input() public config: any;
    @Input() public id: string;
    @Input() public style: any;
    @Input() public navigationData: any;
    public visible: boolean;

    constructor(protected injector: Injector) {
        this.visible = false;
    }

    public onClick() {
        this.visible = !this.visible;
    }

    public navItemClick() {
        this.visible = false;
    }
}

