// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { Component, Input, forwardRef } from '@angular/core';
import { NG_VALUE_ACCESSOR } from '@angular/forms';
import { KsInputBaseComponent } from '@src/app/shared/components/input.base.component';

@Component({
    selector: 'ks-boolean-radio-button-list',
    templateUrl: './boolean-radio-button-list.component.html',
    providers: [
        {
            provide: NG_VALUE_ACCESSOR,
            useExisting: forwardRef(() => KsBooleanRadioButtonListComponent),
            multi: true
        }
    ]
})
export class KsBooleanRadioButtonListComponent extends KsInputBaseComponent {
    @Input() public style: any;

    public changeHandler(event: any): void {
        const value = event && event.srcElement && event.srcElement.value;
        super.updateValue(!!value);
    }

    public getFirstInputId(): string {
        return `${this.id}_1`;
    }

    public getSecondInputId(): string {
        return `${this.id}_2`;
    }
}
