// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
export * from 'kinvey-nativescript-sdk';
export * from 'kinvey-nativescript-sdk/angular';
export { AutoStore } from 'kinvey-js-sdk/lib/datastore/autostore';
