// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { Injectable } from '@angular/core';
import { appKey, appSecret, instanceId } from '@src/assets/config.json';

@Injectable()
export class AppConfigService {
    static settings = {
        appId: '891129c4-6421-4486-a1ee-68678886dc66',
        appName: 'newapp',
        appKey,
        appSecret,
        instanceId
    };

    init() {}
}
