// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { NgModule } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { MessageService } from '@progress/kendo-angular-l10n';

import { AuthenticationService } from '@src/app/core/auth/authentication.service';
import { AuthenticationGuardService } from '@src/app/core/auth/authentication-guard.service';

import { NavigationService } from '@src/app/core/services/navigation.service';
import { StringUtilsService } from '@src/app/core/services/string-utils.service';
import { UtilsService } from '@src/app/core/services/utils.service';
import { KinveyService } from '@src/app/core/data/kinvey.service';
import { DataServiceFactory } from '@src/app/core/data/helpers/data-service.factory';
import { NetworkMonitoringService } from '@src/app/core/services/network-monitoring.service';

import { TranslationsProvider } from '@src/app/core/translations.provider';
import { NotificationService } from '@src/app/core/notification/notification.service';
import { ErrorHandlingService } from '@src/app/core/error-handling.service';
import { EventsService } from '@src/app/core/services/events.service';

import { config, transformConfig } from '@src/app/core/core.config';

const configMeta: NgModule = {
    providers: [
        KinveyService,
        DataServiceFactory,
        NavigationService,
        StringUtilsService,
        UtilsService,
        NetworkMonitoringService,
        TranslationsProvider,
        {
            provide: MessageService,
            useClass: TranslationsProvider
        },
        AuthenticationService,
        AuthenticationGuardService,
        NotificationService,
        ErrorHandlingService,
        EventsService,
        ...config.providers
    ],
    declarations: [
        ...config.declarations
    ],
    imports: [
        HttpClientModule,
        ...config.imports
    ],
    exports: [
        ...config.exports
    ],
    entryComponents: [
        ...config.entryComponents
    ],
    bootstrap: [
        ...config.bootstrap
    ],
    schemas: [
        ...config.schemas
    ],
    id: config.id,
    jit: config.jit
};

transformConfig(configMeta);

@NgModule(configMeta)
export class CoreModule {}
