// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MenusModule } from '@progress/kendo-angular-menu';
import { GridModule } from '@progress/kendo-angular-grid';
import { IntlModule } from '@progress/kendo-angular-intl';
import { InputsModule } from '@progress/kendo-angular-inputs';
import { DateInputsModule } from '@progress/kendo-angular-dateinputs';
import { ButtonsModule } from '@progress/kendo-angular-buttons';
import { DropDownsModule } from '@progress/kendo-angular-dropdowns';
import { ChartsModule } from '@progress/kendo-angular-charts';
import { GaugesModule } from '@progress/kendo-angular-gauges';
import { LabelModule } from '@progress/kendo-angular-label';
import { LayoutModule } from '@progress/kendo-angular-layout';
import { DialogsModule } from '@progress/kendo-angular-dialog';
import { RippleModule } from '@progress/kendo-angular-ripple';
import { KsDataFormComponent } from '@src/app/shared/components/data-form/data-form.component';
import { KsDataPanelComponent } from '@src/app/shared/components/data-panel/data-panel.component';
import { KsGridComponent } from '@src/app/shared/components/grid/grid.component';
import { KsFormComponent } from '@src/app/shared/components/form/form.component';
import { KsAutoCompleteComponent } from '@src/app/shared/components/auto-complete/auto-complete.component';
import { KsComboBoxComponent } from '@src/app/shared/components/combo-box/combo-box.component';
import { KsRadioButtonListComponent } from '@src/app/shared/components/radio-button-list/radio-button-list.component';
import { KsBooleanRadioButtonListComponent } from '@src/app/shared/components/boolean-radio-button-list/boolean-radio-button-list.component';
import { KsMenuComponent } from '@src/app/shared/components/menu/menu.component';
import { KsDropDownListComponent } from '@src/app/shared/components/drop-down-list/drop-down-list.component';
import { KsAreaChartsComponent } from '@src/app/shared/components/area-charts/area-charts.component';
import { KsBarChartsComponent } from '@src/app/shared/components/bar-charts/bar-charts.component';
import { KsLineChartsComponent } from '@src/app/shared/components/line-charts/line-charts.component';
import { KsDonutChartsComponent } from '@src/app/shared/components/donut-charts/donut-charts.component';
import { KsPieChartsComponent } from '@src/app/shared/components/pie-charts/pie-charts.component';
import { KsLanguagesDropDownComponent } from '@src/app/shared/components/languages-drop-down/languages-drop-down.component';
import { KsExpanderComponent } from '@src/app/shared/components/expander/expander.component';
import { KsHamburgerButtonComponent } from '@src/app/shared/components/hamburger-button/hamburger-button.component';

import { ValidationDirective } from '@src/app/shared/directives/validation.directive';
import { FormatValuePipe } from '@src/app/shared/pipes/format-value.pipe';
import { KsNavigationPanelBarComponent } from '@src/app/shared/components/navigation-panel-bar/navigation-panel-bar.component';
import { KsUserDropDownComponent } from '@src/app/shared/components/user-drop-down/user-drop-down.component';
import { ChatComponent } from '@src/app/shared/components/chat/chat.component';
import { KSMapboxComponent } from '@src/app/shared/components/mapbox/mapbox.component';
import { NotificationComponent } from '@src/app/shared/components/notification/notification.component';
import { KsToNotificationIconPipe } from '@src/app/shared/components/notification/to-notification-icon.pipe';

import '@progress/kendo-angular-intl/locales/en/all';

import 'hammerjs';

import { config, transformConfig } from '@src/app/shared/shared.config';

const configMeta: NgModule = {
    providers: [...config.providers],
    declarations: [
        KsDataFormComponent,
        KsDataPanelComponent,
        KsGridComponent,
        KsFormComponent,
        KsAutoCompleteComponent,
        KsComboBoxComponent,
        KsRadioButtonListComponent,
        KsBooleanRadioButtonListComponent,
        KsMenuComponent,
        KsDropDownListComponent,
        KsExpanderComponent,
        KsHamburgerButtonComponent,
        KsAreaChartsComponent,
        KsBarChartsComponent,
        KsLineChartsComponent,
        KsDonutChartsComponent,
        KsPieChartsComponent,
        KsLanguagesDropDownComponent,
        KsNavigationPanelBarComponent,
        KsUserDropDownComponent,
        ValidationDirective,
        FormatValuePipe,
        ChatComponent,
        KSMapboxComponent,
        NotificationComponent,
        KsToNotificationIconPipe,
        ...config.declarations
    ],
    imports: [
        CommonModule,
        MenusModule,
        GridModule,
        TranslateModule,
        ReactiveFormsModule,
        FormsModule,
        IntlModule,
        InputsModule,
        ButtonsModule,
        DateInputsModule,
        DropDownsModule,
        ChartsModule,
        GaugesModule,
        LabelModule,
        LayoutModule,
        DialogsModule,
        RippleModule,
        RouterModule,
        ...config.imports
    ],
    exports: [
        FormsModule,
        ReactiveFormsModule,
        MenusModule,
        GridModule,
        IntlModule,
        InputsModule,
        DateInputsModule,
        ButtonsModule,
        DropDownsModule,
        ChartsModule,
        GaugesModule,
        LabelModule,
        LayoutModule,
        DialogsModule,
        RippleModule,
        TranslateModule,
        KsGridComponent,
        KsFormComponent,
        KsDataFormComponent,
        KsDataPanelComponent,
        KsAutoCompleteComponent,
        KsComboBoxComponent,
        KsRadioButtonListComponent,
        KsBooleanRadioButtonListComponent,
        KsMenuComponent,
        KsDropDownListComponent,
        KsExpanderComponent,
        KsHamburgerButtonComponent,
        KsAreaChartsComponent,
        KsBarChartsComponent,
        KsLineChartsComponent,
        KsDonutChartsComponent,
        KsPieChartsComponent,
        KsLanguagesDropDownComponent,
        KsNavigationPanelBarComponent,
        KsUserDropDownComponent,
        ValidationDirective,
        FormatValuePipe,
        ChatComponent,
        KSMapboxComponent,
        NotificationComponent,
        KsToNotificationIconPipe,
        ...config.exports
    ],
    entryComponents: [...config.entryComponents],
    bootstrap: [...config.bootstrap],
    schemas: [...config.schemas],
    id: config.id,
    jit: config.jit
};

transformConfig(configMeta);

@NgModule(configMeta)
export class SharedModule {}
