// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { NativeScriptCommonModule } from 'nativescript-angular/common';
import { NativeScriptHttpClientModule } from 'nativescript-angular/http-client';

import { NativeScriptFormsModule } from 'nativescript-angular/forms';
import { NativeScriptUIAutoCompleteTextViewModule } from 'nativescript-ui-autocomplete/angular';
import { NativeScriptUICalendarModule } from 'nativescript-ui-calendar/angular';
import { NativeScriptUIChartModule } from 'nativescript-ui-chart/angular';
import { NativeScriptUIDataFormModule } from 'nativescript-ui-dataform/angular';
import { NativeScriptUIGaugeModule } from 'nativescript-ui-gauge/angular';
import { NativeScriptUIListViewModule } from 'nativescript-ui-listview/angular';
import { NativeScriptUISideDrawerModule } from 'nativescript-ui-sidedrawer/angular';
import { NativeChatModule } from '@progress-nativechat/nativescript-nativechat/angular';
import { NativeScriptPickerModule } from 'nativescript-picker/angular';
import { NativeScriptDateTimePickerModule } from 'nativescript-datetimepicker/angular';
import { FontIconPipe } from '@src/app/shared/pipes/font-icon.pipe';

import { HideActionBarDirective } from '@src/app/shared/directives/hide-action-bar.directive';
import { ActionBarControllerDirective } from '@src/app/shared/directives/action-bar-controller.directive';
import { ValidationDirective } from '@src/app/shared/directives/validation.directive';
import { ChatComponent } from '@src/app/shared/components/mobile-chat/chat.component';
import { KSBarcodeScannerComponent } from '@src/app/shared/components/mobile-barcode-scanner/barcode-scanner.component';
import { KSButtonComponent } from '@src/app/shared/components/mobile-button/button.component';
import { KSListViewComponent } from '@src/app/shared/components/mobile-list-view/list-view.component';
import { KSNavigationLabelComponent } from '@src/app/shared/components/mobile-navigation-label/navigation-label.component';
import { KSSearchBarComponent } from '@src/app/shared/components/mobile-search-bar/search-bar.component';
import { KSSignatureComponent } from '@src/app/shared/components/mobile-signature/signature.component';
import { SignatureModalComponent } from '@src/app/shared/components/mobile-signature/signature-modal.component';
import { KsFormComponent } from '@src/app/shared/components/form/form.component';
import { KsGridComponent } from '@src/app/shared/components/grid/grid.component';
import { KSTakePictureComponent } from '@src/app/shared/components/mobile-take-picture/take-picture.component';
import { KsFormButtonComponent } from '@src/app/shared/components/mobile-form-button/form-button.component';
import { KSMapboxComponent } from '@src/app/shared/components/mobile-mapbox/mapbox.component';
import { NotificationComponent } from '@src/app/shared/components/mobile-notification/notification.component';

import { config, transformConfig } from '@src/app/shared/shared.config';

const configMeta: NgModule = {
    providers: [
        ...config.providers
    ],
    declarations: [
        HideActionBarDirective,
        ActionBarControllerDirective,
        ValidationDirective,
        ChatComponent,
        KSBarcodeScannerComponent,
        KSButtonComponent,
        KSListViewComponent,
        KSNavigationLabelComponent,
        KSSearchBarComponent,
        KSSignatureComponent,
        SignatureModalComponent,
        KsFormComponent,
        KsGridComponent,
        KSTakePictureComponent,
        KsFormButtonComponent,
        KSMapboxComponent,
        NotificationComponent,
        FontIconPipe,
        ...config.declarations
    ],
    imports: [
        NativeScriptCommonModule,
        NativeScriptHttpClientModule,
        NativeScriptFormsModule,
        NativeScriptUIAutoCompleteTextViewModule,
        NativeScriptUICalendarModule,
        NativeScriptUIChartModule,
        NativeScriptUIDataFormModule,
        NativeScriptUIGaugeModule,
        NativeScriptUIListViewModule,
        NativeScriptUISideDrawerModule,
        NativeChatModule,
        ReactiveFormsModule,
        NativeScriptPickerModule,
        NativeScriptDateTimePickerModule,
        ...config.imports
    ],
    exports: [
        NativeScriptCommonModule,
        NativeScriptHttpClientModule,
        NativeScriptFormsModule,
        NativeScriptUIAutoCompleteTextViewModule,
        NativeScriptUICalendarModule,
        NativeScriptUIChartModule,
        NativeScriptUIDataFormModule,
        NativeScriptUIGaugeModule,
        NativeScriptUIListViewModule,
        NativeScriptUISideDrawerModule,
        ReactiveFormsModule,
        NativeScriptPickerModule,
        NativeScriptDateTimePickerModule,
        HideActionBarDirective,
        ActionBarControllerDirective,
        ValidationDirective,
        ChatComponent,
        KSBarcodeScannerComponent,
        KSButtonComponent,
        KSListViewComponent,
        KSNavigationLabelComponent,
        KSSearchBarComponent,
        KSSignatureComponent,
        SignatureModalComponent,
        KsFormComponent,
        KsGridComponent,
        KSTakePictureComponent,
        KsFormButtonComponent,
        KSMapboxComponent,
        NotificationComponent,
        FontIconPipe,
        ...config.exports
    ],
    entryComponents: [
        SignatureModalComponent,
        ...config.entryComponents
    ],
    bootstrap: [
        ...config.bootstrap
    ],
    schemas: [
        NO_ERRORS_SCHEMA,
        ...config.schemas
    ],
    id: config.id,
    jit: config.jit
};

transformConfig(configMeta);

@NgModule(configMeta)
export class SharedModule {}
