// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { Component, Input, OnInit, Injector } from '@angular/core';
import { Router } from '@angular/router';

@Component({
    selector: 'ks-menu',
    templateUrl: './menu.component.html',
})
export class KsMenuComponent implements OnInit {
    @Input() public config: any;
    @Input() public id: string;
    @Input() public navigationData: any;
    @Input() public style: any;
    public items: any[];
    private router: Router;

    constructor(protected injector: Injector) {
        this.router = injector.get(Router);
    }

    public onSelect({ item }): void {
        if (!item.items) {
            this.router.navigate([item.path]);
        }
    }

    public ngOnInit() {
        this.items = this.mapItems(this.navigationData);

    }

    // convert the routes to menu items.
    private mapItems(routes: any[]): any[] {
        return routes.map(item => {
            const result: any = {
                text: item.title,
            };

            if (item.routerLink) {
                result.path = item.routerLink;
            }

            if (item.children) {
                result.items = this.mapItems(item.children);
            }

            return result;
        });
    }
}
