// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { AppConfigService } from '@src/app/core/app-config.service';
import { StorageProvider } from '@src/app/core/libs/kinvey-sdk';

export const environmentBase = {
    // To support Firefox, use IndexedDB instead of the default WebSQL storage
    storage: StorageProvider.IndexedDB,
    appId: AppConfigService.settings.appId,
    appName: AppConfigService.settings.appName,
    appKey: AppConfigService.settings.appKey,
    appSecret: AppConfigService.settings.appSecret,
    instanceId: AppConfigService.settings.instanceId
};
