// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { InjectionToken } from '@angular/core';

export const defaultFormValidationMessages = {
    min: '${fieldName} must be ${min} or higher.',
    max: '${fieldName} must be ${max} or lower.',
    required: '${fieldName} is required.',
    email: '${fieldName} must contain a valid email address.',
    minlength: '${fieldName} must be longer than ${requiredLength} characters long.',
    maxlength: '${fieldName} cannot be more than ${requiredLength} characters long.',
    pattern: '${fieldName} must match the following pattern: ${requiredPattern}.',
    url: '${fieldName} must be a valid url.'
};

export const KS_FORM_VALIDATION_MESSAGES = new InjectionToken('KS_FORM_VALIDATION_MESSAGES', {
    providedIn: 'root',
    factory: () => defaultFormValidationMessages
});
