// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { DataStoreType } from '@src/app/core/libs/kinvey-sdk';

export interface DataServiceConfig {
    dataProviderName: string;
    modelTypeName: string;
    serverOperations: boolean;
    createModel: () => any;
    mapData?: (dataItem: any) => any;
    collection: string;
    dataStoreType?: DataStoreType;
    requestOptions?: any;
    pageSize?: number;
    loadOnDemand?: boolean;
}
