// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { NgModule } from '@angular/core';
import { Routes, ExtraOptions } from '@angular/router';
import { NativeScriptRouterModule } from 'nativescript-angular/router';

import * as routeConfig from '@src/app/app-routing.config';

export const defaultRoute = '_app';

const routes: Routes = [
    { path: '', redirectTo: 'system', pathMatch: 'full' },
    { path: 'login', redirectTo: 'system/login', pathMatch: 'full' },
    {
        path: 'system',
        data: { enableDrawer: true },
        loadChildren: '@src/app/modules/system/system.module#SystemModule'
    },
    {
        path: 'main',
        data: { enableDrawer: true },
        loadChildren: '@src/app/modules/main/main.module#MainModule'
    },
    ...routeConfig.config.routes
];

const routeConfigAsAny = routeConfig as any;
if (routeConfigAsAny.transformRoutes) {
    routeConfigAsAny.transformRoutes(routes);
}

const extraOptions: ExtraOptions = routeConfigAsAny.config.extraOptions || {};
const routerConfig: ExtraOptions = {
    enableTracing: extraOptions.enableTracing,
    useHash: extraOptions.useHash,
    initialNavigation: extraOptions.initialNavigation,
    errorHandler: extraOptions.errorHandler,
    preloadingStrategy: extraOptions.preloadingStrategy,
    onSameUrlNavigation: extraOptions.onSameUrlNavigation || 'reload',
    scrollPositionRestoration: extraOptions.scrollPositionRestoration,
    anchorScrolling: extraOptions.anchorScrolling,
    scrollOffset: extraOptions.scrollOffset,
    paramsInheritanceStrategy: extraOptions.paramsInheritanceStrategy,
    malformedUriErrorHandler: extraOptions.malformedUriErrorHandler,
    urlUpdateStrategy: extraOptions.urlUpdateStrategy,
    relativeLinkResolution: extraOptions.relativeLinkResolution
};

@NgModule({
    imports: [NativeScriptRouterModule.forRoot(routes, routerConfig)],
    exports: [NativeScriptRouterModule]
})
export class AppRoutingModule {}
