// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { NgModule } from '@angular/core';
import { Routes, RouterModule, ExtraOptions } from '@angular/router';

import { AuthenticationGuardService } from '@src/app/core/auth/authentication-guard.service';
import { AppLayoutViewComponent } from '@src/app/modules/system/app-layout/app-layout.component';
import { HomeViewComponent } from '@src/app/modules/system/home/home.component';
import { LoginViewComponent } from '@src/app/modules/system/login/login.component';
import { RegisterViewComponent } from '@src/app/modules/system/register/register.component';

import * as routeConfig from '@src/app/app-routing.config';

const routes: Routes = [
    {
        path: '',
        component: AppLayoutViewComponent,
        children: [
            {
                path: '',
                component: HomeViewComponent,
                canActivate: [AuthenticationGuardService],
                runGuardsAndResolvers: 'always'
            },
            {
                path: 'system',
                loadChildren: '@src/app/modules/system/system.module#SystemModule'
            },
            {
                path: 'main',
                loadChildren: '@src/app/modules/main/main.module#MainModule'
            }
        ]
    },
    {
        path: 'login',
        component: LoginViewComponent
    },
    {
        path: 'register',
        component: RegisterViewComponent
    },
    ...routeConfig.config.routes,
    { path: '**', redirectTo: '' }
];

const routeConfigAsAny = routeConfig as any;
if (routeConfigAsAny.transformRoutes) {
    routeConfigAsAny.transformRoutes(routes);
}

const extraOptions: ExtraOptions = routeConfigAsAny.config.extraOptions || {};
const routerConfig: ExtraOptions = {
    enableTracing: extraOptions.enableTracing,
    useHash: extraOptions.useHash,
    initialNavigation: extraOptions.initialNavigation,
    errorHandler: extraOptions.errorHandler,
    preloadingStrategy: extraOptions.preloadingStrategy,
    onSameUrlNavigation: extraOptions.onSameUrlNavigation || 'reload',
    scrollPositionRestoration: extraOptions.scrollPositionRestoration,
    anchorScrolling: extraOptions.anchorScrolling,
    scrollOffset: extraOptions.scrollOffset,
    paramsInheritanceStrategy: extraOptions.paramsInheritanceStrategy,
    malformedUriErrorHandler: extraOptions.malformedUriErrorHandler,
    urlUpdateStrategy: extraOptions.urlUpdateStrategy,
    relativeLinkResolution: extraOptions.relativeLinkResolution
};

@NgModule({
    imports: [RouterModule.forRoot(routes, routerConfig)],
    exports: [RouterModule]
})
export class AppRoutingModule {}
