// -------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
// -------------------------------------------------------------------------
import { Component, OnDestroy, Input } from '@angular/core';

import { Subscription } from 'rxjs';
import { alert, AlertOptions } from 'tns-core-modules/ui/dialogs';

import { NotificationService } from '@src/app/core/notification/notification.service';

@Component({
    selector: 'ks-notification',
    template: ''
})
export class NotificationComponent implements OnDestroy {
    protected subscription: Subscription;

    constructor(protected notificationService: NotificationService) {
        this.subscription = notificationService.subscribe(notification => {
            const alertOptions: AlertOptions = { message: notification.message };

            if (notification.type === 'error') {
                alertOptions.title = 'Error';
            } else if (notification.type === 'info') {
                alertOptions.title = 'Information';
            }

            alert(alertOptions);
        });
    }

    public ngOnDestroy(): void {
        this.subscription.unsubscribe();
    }
}
